import type { DeployCategory, DeployChange } from "./parse-commits"
import { resolveChangeCategory } from "./parse-commits"

export type { DeployCategory }

export interface FeatureFlagReference {
  name: string
  url?: string
}

export interface EnrichedDeployChange {
  category: DeployCategory
  area?: string
  title: string
  description: string
  prNumber?: number
  prUrl?: string
  ticketUrl?: string
  ticketLabel?: "Notion" | "Jira"
  featureFlag?: FeatureFlagReference
  descriptionSource?: "claude" | "rules"
}

interface PullRequestDetails {
  title: string
  body: string
  html_url: string
}

interface VoltArea {
  name: string
  patterns: RegExp[]
}

const VOLT_AREAS: VoltArea[] = [
  {
    name: "Artworks",
    patterns: [/artwork/i, /edition set/i, /\beditions?\b/i, /dimension/i],
  },
  {
    name: "ArtOS",
    patterns: [
      /artos/i,
      /catalog os/i,
      /guided tour/i,
      /welcome popup/i,
      /\bcatalog\b/i,
      /\blists\b/i,
      /show\/fair/i,
      /add to artsy/i,
      /view on artsy cms/i,
      /\bsettings\b/i,
      /instagram/i,
      /mailchimp/i,
      /tearsheet/i,
      /checklist/i,
      /studio editor/i,
      /\bstudio\b/i,
      /collaborator/i,
      /partner cms/i,
      /shareable.*link/i,
    ],
  },
  {
    name: "Conversations",
    patterns: [/conversation/i, /partner offer/i, /\bconvo\b/i, /topaz/i],
  },
  {
    name: "Inventory",
    patterns: [/\binventory\b/i, /artwork management/i],
  },
  {
    name: "Orders",
    patterns: [/\borders?\b/i, /checkout/i],
  },
]

const SCOPE_AREA_MAP: Record<string, string> = {
  lists: "ArtOS",
  conversations: "Conversations",
  artos: "ArtOS",
  inventory: "Inventory",
  orders: "Orders",
  artworks: "Artworks",
}

const TITLE_CASE_SMALL_WORDS = new Set([
  "a",
  "an",
  "and",
  "as",
  "at",
  "for",
  "from",
  "in",
  "of",
  "on",
  "or",
  "the",
  "to",
  "via",
  "with",
])

const BOILERPLATE_LINE =
  /^(<!--|this pr resolves|cc:|created with|generated by|\[wip\]|### |\[[^\]]+\]\(https?:\/\/)/i

export function detectArea(
  title: string,
  body: string,
  scope?: string
): string | undefined {
  if (scope) {
    const mapped = SCOPE_AREA_MAP[scope.toLowerCase()]
    if (mapped) return mapped
  }

  const haystack = `${title}\n${body}`
  for (const area of VOLT_AREAS) {
    if (area.patterns.some(pattern => pattern.test(haystack))) {
      return area.name
    }
  }

  return undefined
}

export function extractTicketLink(
  body: string
): { url: string; label: "Notion" | "Jira" } | undefined {
  const notionMarkdown = body.match(
    /\[(?:notion[^\]]*)\]\((https:\/\/[^)\s]+notion[^)\s]*)\)/i
  )
  if (notionMarkdown?.[1]) {
    return { url: notionMarkdown[1], label: "Notion" }
  }

  const notionUrl = body.match(
    /https?:\/\/(?:www\.)?notion\.(?:so|com)\/[^\s)>"]+/i
  )
  if (notionUrl?.[0]) {
    return { url: notionUrl[0], label: "Notion" }
  }

  const jiraMarkdown = body.match(
    /\[[A-Z]+-\d+\]:\s*(https:\/\/[^\s)>"]+atlassian[^\s)>"]*)/i
  )
  if (jiraMarkdown?.[1]) {
    return { url: jiraMarkdown[1], label: "Jira" }
  }

  const jiraUrl = body.match(
    /https?:\/\/[a-z0-9.-]+\.atlassian\.net\/browse\/[A-Z]+-\d+[^\s)>"]*/i
  )
  if (jiraUrl?.[0]) {
    return { url: jiraUrl[0], label: "Jira" }
  }

  return undefined
}

export function extractFeatureFlag(
  title: string,
  body: string
): FeatureFlagReference | undefined {
  const haystack = `${title}\n${body}`
  const patterns = [
    /remove(?:s|d)?\s+(?:the\s+)?[`"']?([\w-]+)[`"']?\s+feature\s+flag/i,
    /feature\s+flag\s+(?:surrounding\s+)?[`"']?([\w-]+)[`"']?/i,
    /[`"']([\w]+_[\w-]+)[`"']\s+feature\s+flag/i,
    /\b([\w]+_[\w-]+)\s+feature\s+flag/i,
  ]

  let name: string | undefined
  for (const pattern of patterns) {
    const match = haystack.match(pattern)
    if (match?.[1]) {
      name = match[1]
      break
    }
  }

  if (!name) return undefined

  const escapedName = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
  const linkedFlag = haystack.match(
    new RegExp(
      `\\[${escapedName}\\]\\((https?:\\/\\/[^)\\s]+)\\)|https?:\\/\\/[^\\s)>"]*${escapedName}[^\\s)>"]*`,
      "i"
    )
  )

  return {
    name,
    url: linkedFlag?.[1] ?? linkedFlag?.[0],
  }
}

function stripConventionalPrefix(title: string): string {
  return title
    .replace(/^[a-z]+(?:\([^)]+\))?!?:\s*/i, "")
    .replace(/^[A-Z]+-\d+\s*-\s*/, "")
    .trim()
}

export function toTitleCase(text: string): string {
  const words = text.split(/\s+/)

  return words
    .map((word, index) => {
      if (/^artos$/i.test(word)) return "ArtOS"
      if (/^[A-Z]{2,}$/.test(word)) return word
      if (/^artsy$/i.test(word)) return "Artsy"
      if (/^cms$/i.test(word)) return "CMS"
      if (index > 0 && TITLE_CASE_SMALL_WORDS.has(word.toLowerCase())) {
        return word.toLowerCase()
      }
      return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
    })
    .join(" ")
}

export function extractConciseTitle(prTitle: string): string {
  return toTitleCase(stripConventionalPrefix(prTitle))
}

function firstSentence(text: string): string {
  const match = text.match(/^[\s\S]*?[.!?](?:\s|$)/)
  return (match?.[0] ?? text).trim()
}

function shortenDescription(text: string, maxLength = 120): string {
  const sentence = firstSentence(text)
  if (sentence.length <= maxLength) return sentence
  return `${sentence.slice(0, maxLength - 1).trimEnd()}…`
}

function extractDescriptionFromBody(body: string): string | undefined {
  const descriptionSection = body.match(
    /###\s*Description\s*\n+([\s\S]*?)(?:\n###|\n---|$)/i
  )

  const source = descriptionSection?.[1] ?? body
  const paragraphs = source
    .split(/\n\s*\n/)
    .map(paragraph => paragraph.replace(/\s+/g, " ").trim())
    .filter(
      paragraph =>
        paragraph.length > 0 &&
        !BOILERPLATE_LINE.test(paragraph) &&
        !/^https?:\/\//.test(paragraph)
    )

  return paragraphs[0] ? shortenDescription(paragraphs[0]) : undefined
}

function isTooTechnical(text: string): boolean {
  return /`[^`]+`|@\w+\/|\blocalStorage\b|\bProvider\b/i.test(text)
}

function humanizeFallbackDescription(title: string): string {
  let description = stripConventionalPrefix(title)

  if (/^stop\b/i.test(description)) {
    description = description.replace(
      /^stop\s+(.+?)\s+from\s+(.+)$/i,
      "$1 no longer $2"
    )
  } else if (/^remove\b/i.test(description)) {
    description = description.replace(/^remove\s+/i, "Removed the ")
  } else if (/^paginate\b/i.test(description)) {
    description = description.replace(/^paginate\b/i, "Expanded")
  } else if (/^open\b/i.test(description)) {
    description = description.replace(/^open\b/i, "Opens")
  }

  return description.charAt(0).toUpperCase() + description.slice(1)
}

export function humanizeDescription(title: string, body: string): string {
  const fromBody = extractDescriptionFromBody(body)
  if (fromBody && !isTooTechnical(fromBody)) {
    return fromBody.charAt(0).toUpperCase() + fromBody.slice(1)
  }

  return humanizeFallbackDescription(title)
}

function inferSpecialTitle(
  prTitle: string,
  body: string,
  category: DeployCategory
): string | undefined {
  if (category !== "improvements-and-maintenance") return undefined

  const haystack = `${prTitle}\n${body}`.toLowerCase()
  if (/aws-sdk-s3|aws.*s3.*gem/.test(haystack)) {
    return "AWS Storage Library Update"
  }
  if (/selenium-webdriver|selenium/.test(haystack)) {
    return "Test Tooling Update"
  }

  return undefined
}

function inferSpecialDescription(
  specialTitle: string,
  body: string
): string | undefined {
  if (specialTitle === "AWS Storage Library Update") {
    const gemMatch = body.match(/\b([\w-]+)\s+gem\b/i)
    const gemName = gemMatch?.[1] ?? "aws-sdk-s3"
    return `Routine dependency update of the ${gemName} gem, with no visible changes`
  }

  if (specialTitle === "Test Tooling Update") {
    const toolMatch = body.match(/\b([\w-]+)\b/i)
    const toolName = body.toLowerCase().includes("selenium-webdriver")
      ? "selenium-webdriver"
      : (toolMatch?.[1] ?? "test tooling")
    return `Routine update of the ${toolName} tool used for automated browser tests`
  }

  return undefined
}

export function enrichFromPullRequest(
  change: DeployChange,
  pr: PullRequestDetails
): EnrichedDeployChange {
  const ticket = extractTicketLink(pr.body)
  const featureFlag = extractFeatureFlag(pr.title, pr.body)
  const category = resolveChangeCategory(pr.title, change.type)
  const specialTitle = inferSpecialTitle(pr.title, pr.body, category)

  return {
    category,
    area: detectArea(pr.title, pr.body, change.scope),
    title: specialTitle ?? extractConciseTitle(pr.title),
    description:
      (specialTitle && inferSpecialDescription(specialTitle, pr.body)) ??
      humanizeDescription(pr.title, pr.body),
    prNumber: change.prNumber,
    prUrl: pr.html_url,
    ticketUrl: ticket?.url,
    ticketLabel: ticket?.label,
    featureFlag,
    descriptionSource: "rules",
  }
}

export function enrichFromCommit(change: DeployChange): EnrichedDeployChange {
  const title = extractConciseTitle(change.description)

  return {
    category: resolveChangeCategory(undefined, change.type),
    area: detectArea(change.description, "", change.scope),
    title,
    description: humanizeFallbackDescription(change.description),
    prNumber: change.prNumber,
    descriptionSource: "rules",
  }
}

export function formatCopySourceSummary(
  changes: EnrichedDeployChange[]
): string {
  const claudeCount = changes.filter(
    change => change.descriptionSource === "claude"
  ).length
  const rulesCount = changes.length - claudeCount
  return `${claudeCount} claude, ${rulesCount} rules`
}
