name: 🔍 Detect Secrets

on:
  pull_request:

jobs:
  run-detect-secrets:
    uses: artsy/duchamp/.github/workflows/detect-secrets.yml@main
    with:
      baseline-path: ".secrets.baseline" # optional, this is the default
