name: Conventional Commit PR Titles

on:
  workflow_call:

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Validate PR title
        if: github.event.pull_request.draft == false
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const repoName = pr.base.repo.name;
            const semanticFormat = /^(fix|feat|build|chore|ci|docs|style|refactor|perf|test|revert)(?:\(.+\))?!?:.+$/;

            if (!semanticFormat.test(pr.title) && pr.title !== "Deploy") {
              const message = `
              Hi there! :wave:
              We use **Conventional Commit formatting** for PR titles, but your PR title does not appear to follow this.
              Please update your title to follow [Conventional Commits](https://www.conventionalcommits.org) guidelines.  
              `;

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: message
              });

              core.setFailed("PR title does not follow Conventional Commit rules.");
            }
