name: Danger Checks

on:
  workflow_call:
    secrets:
      danger-token:
        required: true
    inputs:
      dangerfile:
        default: "dangerfile.ts"
        required: false
        type: string
      node-version:
        default: "22"
        required: false
        type: string
      use-caller-repo-deps:
        default: false
        required: false
        type: boolean

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Checkout tooling repo
        uses: actions/checkout@v4
        with:
          repository: artsy/duchamp
          ref: main
          path: .tooling

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "${{ inputs.node-version }}"
          cache: yarn
          cache-dependency-path: |
            yarn.lock
            .tooling/yarn.lock

      - name: Install caller packages
        if: ${{ inputs.use-caller-repo-deps }}
        run: yarn install --frozen-lockfile

      - name: Install tooling packages
        if: ${{ !inputs.use-caller-repo-deps }}
        working-directory: .tooling
        run: yarn install --frozen-lockfile

      - name: Run Danger
        working-directory: ${{ github.workspace }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.danger-token }}
          DANGER_BIN: ${{ inputs.use-caller-repo-deps && 'node_modules/.bin/danger' || '.tooling/node_modules/.bin/danger' }}
        run: |
          "$DANGER_BIN" ci \
            --use=typescript \
            --dangerfile "${{ inputs.dangerfile }}"
