name: Danger Yarn Checks

on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
          cache-dependency-path: ${{ github.action_path }}/yarn.lock
      - name: Install tool deps (from this repo)
        working-directory: ${{ github.action_path }}
        run: |
          if yarn --version | grep -q '^1'; then
            yarn install --frozen-lockfile
          else
            yarn install --immutable
          fi
      - name: Run Danger
        working-directory: ${{ github.workspace }}
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.github-token || secrets.GITHUB_TOKEN }}
        run: |
          "${{ github.action_path }}/node_modules/.bin/danger" ci \
            --use=typescript \
            --dangerfile "${{ github.action_path }}/danger-yarn.ts"
