name: Danger Yarn Checks

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Checkout tooling repo
        uses: actions/checkout@v4
        with:
          repository: artsy/duchamp
          ref: main
          path: .tooling

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
          cache-dependency-path: .tooling/yarn.lock

      - name: Install tool deps
        working-directory: .tooling
        run: yarn install --frozen-lockfile

      - name: Run Danger
        working-directory: ${{ github.workspace }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_TOKEN }}
        run: |
          .tooling/node_modules/.bin/danger ci \
            --use=typescript \
            --dangerfile ".tooling/danger-yarn.ts"
