name: Conventional Commit PR Titles

on:
  workflow_call:

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tooling repo
        uses: actions/checkout@v4
        with:
          repository: artsy/duchamp
          ref: PHIRE-2172
          path: .tooling

      - name: Validate PR title
        id: validate-title
        if: github.event.pull_request.draft == false
        uses: actions/github-script@v8
        with:
          script: |
            const pr = context.payload.pull_request;
            const conventionalCommitFormat = /^(fix|feat|build|chore|ci|docs|style|refactor|perf|test|revert)(?:\(.+\))?!?:.+$/;
            const titlePasses = pr.title === 'Deploy' || conventionalCommitFormat.test(pr.title);

            if (titlePasses) {
              console.log("Conventional commit check passed.");
              return true;
            } else {
              console.error("Conventional commit check failed.");
              return false;
            }

      - name: Check result
        run: echo "${{steps.validate-title.outputs.result}}"

      # - name: Leave comment if check failed
      #   uses: actions/github-script@v7
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       await github.rest.issues.createComment({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         issue_number: context.payload.pull_request.number,
      #         body: `## 🚀Deploy reminder

      #         Please **do not** manually merge this deploy PR!

      #         When motion deploys it kills any running tasks in Airflow. We therefore have set up deploy windows so that it automatically deploys at times when we do not expect any tasks to be running. The deploy windows are currently:

      #         - 3pm-5pm UTC
      #         - 7pm-9pm UTC
      #         - 11pm-12am UTC`
      #       });

      # - name: Delete existing comments # if validate PR title passes and already comment
