name: 🔒 NPM Audit

on:
  workflow_call:
    inputs:
      node-version:
        default: "22"
        required: false
        type: string
      fail-on-vulnerabilities:
        default: true
        required: false
        type: boolean
      severity-threshold:
        default: "critical"
        required: false
        type: string

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - run: corepack enable
      - run: corepack install

      - name: Run Yarn Audit (JSON)
        id: audit
        run: |
          set -o pipefail
          yarn npm audit --recursive --json > audit.json || true

      - name: Comment Vulnerabilities
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { commentVulnerabilities } = require('./.tooling/scripts/npm-audit.js');
            await commentVulnerabilities({
              github,
              context,
              core,
              threshold: '${{ inputs.severity-threshold }}',
              auditFilePath: 'audit.json'
            });

      - name: Fail if vulnerabilities found
        if: env.VULNS_FOUND == 'true' && inputs.fail-on-vulnerabilities == true
        run: exit 1